### ISSUE TITLE
Segfault when `markdown->html` is called inside a thread

### ISSUE THREAD

**Issue by subsetpark** [pyrmont/markable#2]
When the following code is evaluated inside of a thread:

```
(markable/markdown->html (string md) [:footnotes])
```

Then a compiled binary segfaults. Here's the valgrind output: https://gist.github.com/subsetpark/adc584986f3b9dbc93e4a972acf70806

**Comment by pyrmont** [comment]
Thanks for the report! I think this was fixed as a result of 8a9973faba851e4cabf2e4bdda453dde95a18b52 but let me know if you keep seeing the behaviour.

**Comment by subsetpark** [comment]
Resolved with https://github.com/pyrmont/markable/commit/8d55732726332c3ae86fb934b2e8c9c10327be72.
